Repository team-suwiki/frontend, pull requests merged in 2023-01, with the labels that each got.

#13 refactor: pages part 1
  package-lock.json
  package.json
  src/api/Auth.js
  src/components/BanFrame.jsx
  src/components/Etc/Button.jsx
  src/components/Etc/Wrapper.jsx
  src/components/Lecture/LectureContainer.jsx
  src/components/List/LectureList.jsx
  src/pages/BanReason.jsx
  src/pages/EmailSignUp.jsx
  src/pages/Exit.jsx
  src/pages/HistoryTest.jsx
  src/pages/IdSearch.jsx
  src/styles/Common.jsx
Labels: enhancement, refactor

#14 refactor: pages part 2 (1/2)
  src/api/Auth.js
  src/index.jsx
  src/pages/HistoryTest.jsx
  src/pages/LectureInfo.jsx
  src/pages/Login.jsx
Labels: enhancement, refactor

#22 refactor: pages part 2 (2/2)
  src/components/Etc/Wrapper.jsx
  src/components/LectureSearch.jsx
  src/components/index.js
  src/hooks/useSearch.js
  src/pages/BanReason.jsx
  src/pages/LectureInfo.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/MyInfo.jsx
  src/pages/MyPosting.jsx
  src/pages/Search.jsx
  src/styles/Common.jsx
Labels: enhancement, refactor

#23 refactor: search 페이지 최적화(메인,검색 필터선택 제작)
  src/components/List/MainList.jsx
  src/components/OptionSelect.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/Search.jsx
  src/pages/SignUp.jsx
  src/styles/Common.jsx
Labels: enhancement, refactor

#26 refactor: 컴포넌트 최적화
  .eslintrc.json
  package.json
  src/components/Lecture/LectureContainer.jsx
  src/components/Major/MajorSearch.jsx
  src/components/Nav.jsx
  src/components/UserInfo/UserAccount.jsx
  src/components/UserInfo/UserInfo.jsx
  src/utils/loginStorage.js
Labels: refactor

#27 refactor: react-query 모듈화 진행
  src/components/Lecture/IsTestInfo.jsx
  src/components/List/EvaluationList.jsx
  src/components/List/LectureList.jsx
  src/components/List/MainList.jsx
  src/components/List/SearchEvaluationList.jsx
  src/components/List/TestInfoList.jsx
  src/hooks/useLectureQuery.js
  src/hooks/useUserQuery.js
Labels: refactor

#28 fix: 로그인 상태 버그 수정
  src/components/Nav.jsx
  src/utils/loginStorage.js
Labels: bug

#29 refactor: modal 최적화 (react-modal 제거)
  package-lock.json
  package.json
  src/components/Etc/Modal.jsx
  src/components/Etc/ModalStyle.js
  src/components/List/EvaluationList.jsx
  src/components/List/TestInfoList.jsx
  src/components/Major/MajorSearch.jsx
  src/components/Major/MajorSelect.jsx
  src/components/Write/WriteEvaluation.jsx
  src/components/Write/WriteTestInfo.jsx
  src/components/index.js
  src/pages/LectureInfo.jsx
Labels: refactor

#31 refactor: Lecture폴더 컴포넌트 최적화 작업
  src/api/ApiController.js
  src/app/versionCheck.js
  src/components/EvaluationDetail.jsx
  src/components/Lecture/IsTestInfo.jsx
  src/components/Lecture/LectureCard.jsx
  src/components/Lecture/LectureDetail.jsx
  src/components/Lecture/LectureInfoBox.jsx
  src/components/List/EvaluationList.jsx
  src/components/List/MainList.jsx
  src/components/List/SearchEvaluationList.jsx
  src/components/List/SearchTestInfoList.jsx
  src/components/Major/MajorSearch.jsx
  src/hooks/useLectureQuery.js
  src/utils/floatFix.js
Labels: refactor

#32 refactor: 메서드 모듈화 / 네비게이트 관련 버그 수정 / api 리팩토링
  src/api/ApiController.js
  src/api/Auth.js
  src/api/Lecture.js
  src/api/Major.js
  src/api/User.js
  src/api/etc.js
  src/app/recoilStore.js
  src/app/versionCheck.js
  src/components/Etc/Modal.jsx
  src/components/Etc/RangeInput.jsx
  src/components/Etc/ScrollButton.jsx
  src/components/Lecture/IsTestInfo.jsx
  src/components/Lecture/LectureDetail.jsx
  src/components/List/EvaluationList.jsx
  src/components/List/LectureList.jsx
  src/components/List/MainList.jsx
  src/components/List/SearchEvaluationList.jsx
  src/components/List/SearchTestInfoList.jsx
  src/components/List/TestInfoList.jsx
  src/components/Major/MajorSearch.jsx
  src/components/Nav.jsx
  src/components/OptionSelect.jsx
  src/components/SemesterSelect.jsx
  src/components/UserInfo/UserInfo.jsx
  src/components/Write/WriteEvaluation.jsx
  src/components/Write/WriteTestInfo.jsx
  src/constants/cacheTime.js
  src/constants/placeholderData.js
  src/hooks/useLectureQuery.js
  src/hooks/useUserQuery.js
  src/index.jsx
  src/pages/Exit.jsx
  src/pages/IdSearch.jsx
  src/pages/LectureInfo.jsx
  src/pages/Login.jsx
  src/pages/Main.jsx
  src/pages/MyInfo.jsx
  src/pages/PwSearch.jsx
  src/pages/ResetPassword.jsx
  src/pages/Search.jsx
  src/pages/SignUp.jsx
  src/styles/Common.jsx
  src/utils/loginStorage.js
  src/utils/scrollToTop.js
Labels: bug, refactor

#33 refactor: API 나머지 리팩토링 작업 및 전공선택 모달 커스텀 훅 생성
  src/api/ApiController.js
  src/api/Lecture.js
  src/api/Major.js
  src/api/Notice.js
  src/api/etc.js
  src/components/Major/MajorSearch.jsx
  src/hooks/useFavoriteMajor.js
  src/hooks/useSearch.js
Labels: refactor

#34 fix: 토큰 리프레시 관련 에러 수정
  src/api/ApiController.js
Labels: bug
